- name: Install Nginx
  hosts: all
  tasks:
    - name: Install Nginx
      yum:
       name: nginx
       state: present
    
    - name: allow all access to tcp port 80
      firewalld:
       port: 80/tcp
       zone: public
       state: enabled

    - name: Start Nginx
      service:
       name: nginx
       state: started
