- name: Install Nginx
  hosts: all
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      become: yes
      become_method: sudo
      become_user: root
    
    - name: allow all access to tcp port 80
      firewalld:
        port: 80/tcp
        zone: public
        state: enabled
      become_method: sudo
      become_user: root

    - name: Start Nginx
      service:
        name: httpd
        state: started
      become_method: sudo
      become_user: root
